spring.cloud:
  stream:
    function.routing.enabled: true
    kafka:
      binder:
        brokers: localhost
        defaultBrokerPort: 9092
        autoCreateTopics: true
    bindings:
      charCountFn-in-0:
        destination: input
      charCountFn-out-0:
        destination: output
  function:
    scan:
      enabled: true
      packages: com.yuknis.logs.demo.functions
    definition: charCountFn